using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System.Linq;
using TMPro;
using Photon.Pun.UtilityScripts;
using UnityEngine.SceneManagement;

public class Main : MonoBehaviour
{
    //public float fallTime = 1f;
    //public float previousTime;
    //public Vector3 rotationPoint;
    // Start is called before the first frame update

    [SerializeField]
    SoundManager soundManager;

    //[SerializeField]
    //ParentCollision parentCollision;

    [SerializeField]
    SquareManager squareManager;

    [SerializeField]
    PlayerInput playerInput;

    [SerializeField]
    GridObjectManager gridObjectManager;

    [SerializeField]
    GridObserver gridObserver;

    [SerializeField]
    Debugmanager debugManager;

    [SerializeField]
    Judgemanager judgeManager;

    [SerializeField]
    TimerData timerData;

    [Range(0, 10)]
    public float holizontalMoveSpeed;

    [Range(0, 10)]
    public float verticalMoveSpeed;

    [Range(0, 5)]
    public float virticalFallSpeed;

    [Range(0, 5)]
    public float specialDelayTime;

    [Range(0, 5)]
    public float delayTime;

    [SerializeField] private Image uiFill;
    [SerializeField] private TextMeshProUGUI uiText;
    [SerializeField] private float CountTime = 10;

    LayerMask gridMask = 1 << 6;

    LayerMask objectMask = 1 << 7;

    public float rotateSpeed;//add

    int gamePhase = 0;

    bool pastDelete = false;

    float time;

    //int combo;

    //squareManager.startInit();
    private void Awake()
    {
        time = CountTime;
        timerData.TimeInit(uiFill, uiText, CountTime,time);
        
    }
    void Start()
    {
        //combo = 0;
        if (SceneManager.GetActiveScene().name == "MainEasyMode")
        {

            SquareManager.ballnumbers = 4;
        }
        else SquareManager.ballnumbers = 5;
        judgeManager.ScoreInit();
        soundManager.AudioInit();
        gridObjectManager.GridInit();
        squareManager.startInit();
        //debugManager.DebugTextInit(gridObjectManager.GridSquare, debugManager.tmpTemplate, debugManager.InfoDebugTextArray, debugManager.DebugTextParent);

        gridObserver.ArrayInfoInit(gridObserver.gameSquareInfoArray);
        gridObserver.ArrayBoolInfoInit(gridObserver.gameSquareBoolArray);
        gamePhase = 1;
    }

    // Update is called once per frame
    void Update()
    {
        //if (Input.GetKeyDown(KeyCode.Space))
        //{


        //    Debug.Log(gamePhase);
        //    //gamePhase = 3;
        //}
        float timer = CountTime;
        CountTime = timerData.TimeCount(uiFill,uiText,timer,time);
        switch (gamePhase)
        {
            case 1:
               // combo = 0;
                squareManager.squareParentInit();
                //judgeManager.ComboInit();
                squareManager.nowSquareInit();
                squareManager.nextSquareInit();
               // parentCollision.ParentInit();

                gamePhase = 2;
                break;
            case 2:
                
                //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½Fï¿½[ï¿½Y
                squareManager.SquareMove(playerInput.MoveKeyInput(), holizontalMoveSpeed, virticalFallSpeed, 0f, gridObjectManager.GridSquare, verticalMoveSpeed, playerInput.RotateKeyInput());
                //sphereManager.SphereRotate(playerInput.RotateKeyInput(), 100);
                if (Input.GetKeyDown(KeyCode.E) && squareManager.srot == true)//add
                {
                    squareManager.srot = false;
                    StartCoroutine(squareManager.Rotate(rotateSpeed, 1f));
                }
                else if (Input.GetKeyDown(KeyCode.F) && squareManager.srot == true)//add
                {
                    squareManager.srot = false;
                    StartCoroutine(squareManager.Rotate(rotateSpeed, -1f));
                }

                else if (squareManager.Raycast2D(objectMask) < 0.1f && squareManager.Raycast2D(objectMask) != 0f)
                {

                    
                    //Debug.Log("spaceã¼ãŸã‚“ã‚’ã‚¯ãƒªãƒƒã‚¯ã—ã¦ã‚‹" + gamePhase);
                    gamePhase = 3;
                }
                else if (Input.GetKeyDown(KeyCode.Space))
                {
                    //Debug.Log(squareManager.squareParent.transform.rotation.z);
                    if (squareManager.squareParent.transform.rotation.z % 90 > 1) return;
                    float drop = squareManager.Raycast2D(objectMask);
                    squareManager.SquareDrop(drop);
                    gamePhase = 3;
                }

                //if (Input.GetKeyDown(KeyCode.LeftArrow))
                //{
                //    squareManager.squareParent.transform.position += new Vector3(-1, 0, 0);
                //}
                //else if(Input.GetKeyDown(KeyCode.RightArrow))
                //{
                //    squareManager.squareParent.transform.position += new Vector3(1, 0, 0);
                //}
                break;
            case 3:
                squareManager.zeroRigid();
                gridObserver.GridTrack(squareManager.nowSquareArray, 0.5f, gridMask, gridObserver.gameSquareInfoArray, squareManager.gameSquareArray, gridObjectManager.gridObjectArray, 500);

                for (int n = 0; n < gridObserver.gameSquareInfoArray.Length; n++)
                {
                    
                    if (gridObserver.gameSquareInfoArray[n] < 1)
                    {
                        continue;
                    }
                    //squareManager.gameSquareArray[n].transform.rotation = Quaternion.identity;
                    squareManager.gameSquareArray[n].transform.position = gridObjectManager.gridObjectArray[n].transform.position;
                    
                    //debugManager.InfoTextRegistration(n, debugManager.InfoDebugTextArray, gridObserver.gameSquareInfoArray);
                    //debugManager.BoolTextRegistration(n, debugManager.InfoDebugTextArray, gridObserver.gameSphereBoolArray);
                    gridObjectManager.gridObjectArray[n].SetActive(true);
                }


                gamePhase = 4;
                break;
            case 4:
                gridObserver.FallBallIndexList.Clear();
                bool animate = false;
                for (int i = 0; i < gridObserver.gameSquareInfoArray.Length; i++)
                {
                    //0.ï¿½ï¿½ï¿½ï¿½ï¿½Â”\ï¿½ï¿½ï¿½zï¿½ï¿½ 1ï¿½ÌƒCï¿½ï¿½ï¿½fï¿½bï¿½Nï¿½Xï¿½Ì‚ÝŒvï¿½Zï¿½Xï¿½^ï¿½[ï¿½g
                    //1.ï¿½ï¿½ï¿½ï¿½ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½ÌŽï¿½ï¿½ï¿½4ï¿½Â‚ï¿½ï¿½ï¿½ï¿½ï¿½
                    //2.22 ï¿½ÌŽï¿½ n = 2 ï¿½ï¿½ï¿½ï¿½ÈŠOï¿½ï¿½1
                    gridObserver.NumFallPossibilitySet(i, gridObserver.gameSquareInfoArray, gridObserver.gameSquareBoolArray, pastDelete);

                    //debugManager.InfoTextRegistration(i, debugManager.InfoDebugTextArray, gridObserver.gameSquareInfoArray);
                    //debugManager.BoolTextRegistration(i, debugManager.InfoDebugTextArray, gridObserver.gameSphereBoolArray);

                    //ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½Íƒï¿½ï¿½^ï¿½[ï¿½ï¿½
                    if (gridObserver.gameSquareBoolArray[i] != 1)
                    {
                        continue;
                    }

                    FallMethodAll(i);
                    

                    animate = true;
                }

                if (animate)
                {
                    //ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                    //Debug.Log("ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Jï¿½n");
                    gamePhase = 5;
                }
                else
                {

                    soundManager.FalledSound();
                    StartCoroutine(judgeManager.ScoreAnimation(4.0f, 0.2f));
                    //ï¿½wï¿½Lï¿½Tï¿½Sï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½Fï¿½[ï¿½Yï¿½ï¿½
                    gamePhase = 7;
                }
                break;
            case 5:
                
                for (int i = 0; i < gridObserver.FallBallIndexList.Count; i++)
                {

                    //Debug.Log(gridObserver.FallBallIndexList.Count);
                    int iNum = gridObserver.FallBallIndexList[i][0];
                    int iNumInto = gridObserver.FallBallIndexList[i][1];
                    //for (int j = 0; j < gridObserver.FallBallIndexList.Count; j++)
                    //{
                    //    Debug.Log(gridObserver.FallBallIndexList[j][0]);
                    //}


                    //Debug.Log(iNum + "ï¿½ï¿½ï¿½ï¿½" + iNumInto + "ï¿½ï¿½");

                    //sphereManager.SphereFallAnimationOmega(iNum, iNumInto, gridObjectManager.gridObjectArray, sphereManager.gameSphereArray, 0.2f);

                    squareManager.SquareFallAnimationAlfa(iNum, iNumInto, gridObjectManager.gridObjectArray, squareManager.gameSquareArray);
                    
                    squareManager.gameSquareArray[iNumInto] = squareManager.gameSquareArray[iNum];
                    //Debug.Log(iNum + "ï¿½ï¿½" + iNumInto + "ï¿½É“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½");
                    //Debug.Log("ï¿½ï¿½ï¿½Xï¿½gï¿½Ì‚È‚ï¿½ï¿½ï¿½:" + (gridObserver.FallBallIndexList.Count - 1));
                    //gridObserver.FallBallIndexList.RemoveAt(i);
                }
                gridObserver.FallBallIndexList.Clear();
                
                if (gridObserver.FallBallIndexList.Count < 1)
                {
                    //ï¿½ï¿½ï¿½ÌƒXï¿½eï¿½bï¿½v
                   // Debug.Log("ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½");
                    gamePhase = 4;
                    
                }
                else
                {
                    
                    //ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½tï¿½Fï¿½[ï¿½Yï¿½Jï¿½ï¿½Ô‚ï¿½
                    //Debug.Log("ï¿½ï¿½ï¿½ÌˆÊ’uï¿½F" + sphereManager.gameSphereArray[Number].transform.position.x.ToString("f2") + ","
                    //    + sphereManager.gameSphereArray[Number].transform.position.y.ToString("f2"));
                    //Debug.Log("ï¿½Ú“Iï¿½nï¿½F" + gridObjectManager.gridObjectArray[NumInto].transform.position.x.ToString("f2") + ","
                    //    + gridObjectManager.gridObjectArray[NumInto].transform.position.y.ToString("f2"));
                    gamePhase = 5;
                }
                break;
            case 7:
               // Debug.Log("hanntei ");
                int Keseta = judgeManager.ShapeJudgement(gridObserver.gameSquareInfoArray, squareManager.gameSquareArray, gridObserver.gameSquareBoolArray);
                if (Keseta == 0)
                {
                    //ï¿½ï¿½ï¿½Ìƒsï¿½[ï¿½Xï¿½ð—Ž‚Æ‚ï¿½
                    pastDelete = false;
                    for (int n = 0; n < gridObserver.gameSquareInfoArray.Length; n++)
                    {

                        if (gridObserver.gameSquareInfoArray[n] < 1)
                        {
                            continue;
                        }
                        //squareManager.gameSquareArray[n].transform.rotation = Quaternion.identity;
                        squareManager.gameSquareArray[n].transform.position = gridObjectManager.gridObjectArray[n].transform.position;
                        
                    }
                    for (int i = 120; i < 140; i++)
                    {
                        if (gridObserver.gameSquareBoolArray[i] != 2)
                        {
                            continue;
                        }
                        gamePhase = 9;
                        return;
                    }
                    gamePhase = 1;
                    //Debug.Log("kesenai");
                }
                else if (Keseta == 1)
                {
                    for (int n = 0; n < gridObserver.gameSquareInfoArray.Length; n++)
                    {

                        if (gridObserver.gameSquareInfoArray[n] < 1)
                        {
                            continue;
                        }
                        //squareManager.gameSquareArray[n].transform.rotation = Quaternion.identity;
                        squareManager.gameSquareArray[n].transform.position = gridObjectManager.gridObjectArray[n].transform.position;
                    }
                    //ï¿½Ä“xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                    //Debug.Log("1");
                    StartCoroutine(DelayedGamePhase4(delayTime));
                    //Debug.Log("2");
                    pastDelete = true;
                    gamePhase = 8;
                }
                else
                {
                    for (int n = 0; n < gridObserver.gameSquareInfoArray.Length; n++)
                    {

                        if (gridObserver.gameSquareInfoArray[n] < 1)
                        {
                            continue;
                        }

                        squareManager.gameSquareArray[n].transform.position = gridObjectManager.gridObjectArray[n].transform.position;
                    }
                    //Debug.Log("ï¿½Xï¿½yï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½");

                    //StartCoroutine(DelayedGamePhase4(specialDelayTime * (Keseta - 1)));//add Kesetaï¿½Í“ï¿½ï¿½ï¿½Gï¿½tï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Å‚ï¿½ï¿½ï¿½Âï¿½+1ï¿½ÉÝ’è‚µï¿½Ä‚ï¿½ï¿½ï¿½iï¿½Ó–ï¿½ï¿½í‚©ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½Ç“sï¿½ï¿½ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½jï¿½Ì‚ÅA-1ï¿½ï¿½ï¿½ï¿½ï¿½ÄŒÂï¿½ï¿½ï¿½ï¿½Ò‹@ï¿½ï¿½ï¿½Ô‚ï¿½Ý’ï¿½
                    //Debug.Log("2");
                    gamePhase = 10;
                }

                //gamePhase = 1;
                break;
            case 8:
                
                break;
            case 9:
                //ã‚²ãƒ¼ãƒ ã‚ªãƒ¼ãƒãƒ¼æ™‚ã«ã“ã“ã«å…¥ã‚‹
                SendMessage("SoloSceneMovetoResult");
                break;
            case 10:
                if (judgeManager.isbreakfinish)
                {
                    pastDelete = true;
                    gamePhase = 4;
                }
                break;
            default:
                break;
        }
    }
    IEnumerator DelayedGamePhase4(float delay)//addï¿½@ï¿½Gï¿½tï¿½Fï¿½Nï¿½gï¿½Ò‹@ï¿½pï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½iï¿½Ò‹@ï¿½ï¿½ï¿½ï¿½gamephase=8ï¿½j
    {
        yield return new WaitForSeconds(delay);

        
        pastDelete = true;
        gamePhase = 4;
       
        
        //Debug.Log("1.5");
    }
    void FallMethodAll(int number)
    {
        //3.n = 1 ï¿½@ï¿½ÌŽï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½zï¿½ï¿½ï¿½ï¿½mï¿½F ï¿½ï¿½ï¿½ï¿½ï¿½ÌˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½mï¿½F ï¿½ï¿½ï¿½ï¿½ï¿½Â”\ï¿½ï¿½ï¿½zï¿½ï¿½yï¿½Ñï¿½ï¿½ï¿½ï¿½zï¿½ï¿½ï¿½nï¿½ï¿½0ï¿½É‚ï¿½ï¿½ï¿½
        //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½numInto
        int numInto = gridObserver.ReturnNumFallInto(number, gridObserver.gameSquareInfoArray);

        //4.ï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½
        gridObserver.NumFall(number, numInto, gridObserver.gameSquareInfoArray, gridObserver.gameSquareBoolArray);

        //ï¿½ï¿½ï¿½ï¿½ï¿½Â”\ï¿½ï¿½ï¿½ÌÄŠmï¿½Fï¿½Aï¿½zï¿½ï¿½Ö‚Ì‘ï¿½ï¿½
        gridObserver.NumFallPossibilitySet(numInto, gridObserver.gameSquareInfoArray, gridObserver.gameSquareBoolArray, pastDelete);

        gridObserver.FallBallAddToList(number, numInto);
        //ï¿½fï¿½oï¿½bï¿½Oï¿½eï¿½Lï¿½Xï¿½g
        //debugmanager.infotextregistration(number, debugmanager.infodebugtextarray, gridobserver.gamesphereinfoarray);
        //debugmanager.infotextregistration(numinto, debugmanager.infodebugtextarray, gridobserver.gamesphereinfoarray);

        //debugmanager.booltextregistration(number, debugmanager.infodebugtextarray, gridobserver.gamesphereboolarray);
        //debugmanager.booltextregistration(numinto, debugmanager.infodebugtextarray, gridobserver.gamesphereboolarray);

        //StartCoroutine(sphereManager.SphereFallCoroutine(number, numInto, gridObjectManager.gridObjectArray, sphereManager.gameSphereArray));
    }

    //private void SquareMove()
    //{
    //    // ï¿½ï¿½ï¿½ï¿½ï¿½Lï¿½[ï¿½Åï¿½ï¿½É“ï¿½ï¿½ï¿½
    //    if (Input.GetKeyDown(KeyCode.LeftArrow))
    //    {
    //        transform.position += new Vector3(-1, 0, 0);
    //    }
    //    // ï¿½Eï¿½ï¿½ï¿½Lï¿½[ï¿½Å‰Eï¿½É“ï¿½ï¿½ï¿½
    //    else if (Input.GetKeyDown(KeyCode.RightArrow))
    //    {
    //        transform.position += new Vector3(1, 0, 0);
    //    }
    //    // ï¿½ï¿½ï¿½ï¿½ï¿½Å‰ï¿½ï¿½ÉˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚ÂAï¿½ï¿½ï¿½ï¿½ï¿½Lï¿½[ï¿½Å‚ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½
    //    else if (Input.GetKeyDown(KeyCode.DownArrow) || Time.time - previousTime >= fallTime)
    //    {
    //        transform.position += new Vector3(0, -1, 0);
    //        previousTime = Time.time;
    //    }
    //    else if (Input.GetKeyDown(KeyCode.UpArrow))
    //    {
    //        transform.RotateAround(transform.TransformPoint(rotationPoint), new Vector3(0, 0, 1), 90);
    //    }
    //}

}
